# Generated by Django 4.1.2 on 2023-01-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=5)),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.BigIntegerField()),
                ('ebitda', models.BigIntegerField()),
                ('revenue_growth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=100)),
                ('fulltime_employees', models.IntegerField(blank=True, null=True)),
                ('long_business_summary', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
